package com.wondersgroup.website.bo;

// Generated 2014-7-7 10:45:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;


/**
 * CaseItem generated by hbm2java
 */
@Entity
@Table(name = "CASE_ITEM", schema = "SCFDA")
public class CaseItem extends BaseBo{

	/**
	 * serialVersionUID : TODO
	 */
	private String caseid;
	//业务来源
	private String caseywly;
	//来电号码
	private String caseldhm;
	//业务类别
	private String caseywlb;
	//业务类型
	private String caseywlx;
	//创建时间
	private Date createdate;
	//创建人
	private String creater;
	//创建人姓名
	private String createname;
	//工单状态
	private String casestatus;
	//投诉时间
	private Date casetssj;
	//工单办结时间
	private Date casebjsj;
	//工单受理时间
	private Date caseslsj;
	//期限
	private String caseqx;
	//省
	private String casewtgsd_sheng;
	//市
	private String casewtgsd_shi;
	//区
	private String casewtgsd_xian;
	
	//是否保密
	private String casesfbm;
	//姓名类型
	private String casetsrxmlx;
	//投诉人姓名
	private String casetsrxm;
	//投诉人电话
	private String casetsrdh;
	//投诉人证件类型
	private String casezjlx;
	//投诉人证件号码
	private String casetsrzjhm;
	//投诉人电子邮箱
	private String casetsrdzyx;
	//投诉人通讯地址
	private String casetsrdz;
	//投诉人邮政编码
	private String casetsryzbm;
	//投诉人是否职业举报
	private String casesfzyjb;
	//被投诉人名称
	private String casemc;
	//被投诉人产品名称
	private String casecpmc;
	//被投诉人联系电话
	private String casebtslxdh;
	//被投诉人通讯地址
	private String casebtstxdz;
	//被投诉人批准文号
	private String casebtspzwh;
	//被投诉人产品规格
	private String casebtscpgg;
	//被投诉人产品批号
	private String casebtscpph;
	//被投诉人生产厂家
	private String casebtssccj;
	//被投诉人销售企业
	private String casebtsxsqy;
	//被投诉人产品生产日期
	private Date casecpscrq;
	//被投诉人产品有效期
	private String casebtscpyxq;
	//标题
	private String casebt;
	//关键词
	private String casegjc;
	//主要内容
	private String caseywnr;
	//处理意见
	private String caseclyj;
	//问题分类名称
	private String casewtflmc;
	//问题分类code
	private String casewtflcode;
	//产品分类名称	
	private String casecpflmc;
	//产品分类code
	private String casecpflcode;
	//紧急程度
	private String casejjcd;
	//回复方式
	private String casehffs;
	//回访地址
	private String casehfdz;
	//与上传文件表caseid相对应
	private String uploadfileid;
	//是否有上传文件
	private String casebtssffj;
	//坐席单位编码
	private String casedjrow;
	//交换标识
	private String jhbs;
	//查询码
	private String cym;
	//电话唯一标识
	private String callid;
	//机关id
	private String organid;
	public CaseItem() {
	}

	public CaseItem(String caseid) {
		this.caseid = caseid;
	}
	
	
	@Column(name = "CASELDHM", length = 20)
	public String getCaseldhm() {
		return caseldhm;
	}

	public void setCaseldhm(String caseldhm) {
		this.caseldhm = caseldhm;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CASETSSJ", length = 7)
	public Date getCasetssj() {
		return casetssj;
	}

	public void setCasetssj(Date casetssj) {
		this.casetssj = casetssj;
	}

	@Column(name = "CASEWTGSD_SHENG", length = 32)
	public String getCasewtgsd_sheng() {
		return casewtgsd_sheng;
	}

	public void setCasewtgsd_sheng(String casewtgsdSheng) {
		casewtgsd_sheng = casewtgsdSheng;
	}

	@Column(name = "CASEWTGSD_SHI", length = 32)
	public String getCasewtgsd_shi() {
		return casewtgsd_shi;
	}

	public void setCasewtgsd_shi(String casewtgsdShi) {
		casewtgsd_shi = casewtgsdShi;
	}

	@Column(name = "CASEWTGSD_XIAN", length = 32)
	public String getCasewtgsd_xian() {
		return casewtgsd_xian;
	}

	public void setCasewtgsd_xian(String casewtgsdXian) {
		casewtgsd_xian = casewtgsdXian;
	}

	@Column(name = "CASESFBM", length = 2)	
	public String getCasesfbm() {
		return casesfbm;
	}

	public void setCasesfbm(String casesfbm) {
		this.casesfbm = casesfbm;
	}

	@Column(name = "CASETSRXMLX", length = 25)
	public String getCasetsrxmlx() {
		return casetsrxmlx;
	}

	public void setCasetsrxmlx(String casetsrxmlx) {
		this.casetsrxmlx = casetsrxmlx;
	}

	@Column(name = "CASETSRXM", length = 25)
	public String getCasetsrxm() {
		return casetsrxm;
	}

	public void setCasetsrxm(String casetsrxm) {
		this.casetsrxm = casetsrxm;
	}

	@Column(name = "CASETSRDH", length = 25)
	public String getCasetsrdh() {
		return casetsrdh;
	}

	public void setCasetsrdh(String casetsrdh) {
		this.casetsrdh = casetsrdh;
	}

	@Column(name = "CASEZJLX", length = 100)
	public String getCasezjlx() {
		return casezjlx;
	}

	public void setCasezjlx(String casezjlx) {
		this.casezjlx = casezjlx;
	}

	@Column(name = "CASETSRZJHM", length = 25)
	public String getCasetsrzjhm() {
		return casetsrzjhm;
	}

	public void setCasetsrzjhm(String casetsrzjhm) {
		this.casetsrzjhm = casetsrzjhm;
	}

	@Column(name = "CASETSRDZYX", length = 64)
	public String getCasetsrdzyx() {
		return casetsrdzyx;
	}

	public void setCasetsrdzyx(String casetsrdzyx) {
		this.casetsrdzyx = casetsrdzyx;
	}

	@Column(name = "CASETSRDZ", length = 200)
	public String getCasetsrdz() {
		return casetsrdz;
	}

	public void setCasetsrdz(String casetsrdz) {
		this.casetsrdz = casetsrdz;
	}

	@Column(name = "CASETSRYZBM", length = 6)
	public String getCasetsryzbm() {
		return casetsryzbm;
	}

	public void setCasetsryzbm(String casetsryzbm) {
		this.casetsryzbm = casetsryzbm;
	}

	@Column(name = "CASESFZYJB", length = 2)
	public String getCasesfzyjb() {
		return casesfzyjb;
	}

	public void setCasesfzyjb(String casesfzyjb) {
		this.casesfzyjb = casesfzyjb;
	}

	@Column(name = "CASEMC", length = 100)
	public String getCasemc() {
		return casemc;
	}

	public void setCasemc(String casemc) {
		this.casemc = casemc;
	}

	@Column(name = "CASECPMC", length = 4000)
	public String getCasecpmc() {
		return casecpmc;
	}

	public void setCasecpmc(String casecpmc) {
		this.casecpmc = casecpmc;
	}

	@Column(name = "CASEBTSLXDH", length = 32)
	public String getCasebtslxdh() {
		return casebtslxdh;
	}

	public void setCasebtslxdh(String casebtslxdh) {
		this.casebtslxdh = casebtslxdh;
	}

	@Column(name = "CASEBTSTXDZ", length = 200)
	public String getCasebtstxdz() {
		return casebtstxdz;
	}

	public void setCasebtstxdz(String casebtstxdz) {
		this.casebtstxdz = casebtstxdz;
	}

	@Column(name = "CASEBTSPZWH", length = 100)
	public String getCasebtspzwh() {
		return casebtspzwh;
	}

	public void setCasebtspzwh(String casebtspzwh) {
		this.casebtspzwh = casebtspzwh;
	}

	@Column(name = "CASEBTSCPGG", length = 60)
	public String getCasebtscpgg() {
		return casebtscpgg;
	}

	public void setCasebtscpgg(String casebtscpgg) {
		this.casebtscpgg = casebtscpgg;
	}
	
	@Column(name = "CASEBTSCPPH", length = 50)
	public String getCasebtscpph() {
		return casebtscpph;
	}

	public void setCasebtscpph(String casebtscpph) {
		this.casebtscpph = casebtscpph;
	}

	
	@Column(name = "CASEBTSSCCJ", length = 200)
	public String getCasebtssccj() {
		return casebtssccj;
	}

	public void setCasebtssccj(String casebtssccj) {
		this.casebtssccj = casebtssccj;
	}

	@Column(name = "CASEBTSXSQY", length = 200)
	public String getCasebtsxsqy() {
		return casebtsxsqy;
	}

	public void setCasebtsxsqy(String casebtsxsqy) {
		this.casebtsxsqy = casebtsxsqy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CASECPSCRQ", length = 7)
	public Date getCasecpscrq() {
		return casecpscrq;
	}

	public void setCasecpscrq(Date casecpscrq) {
		this.casecpscrq = casecpscrq;
	}

	@Column(name = "CASEBTSCPYXQ", length = 32)
	public String getCasebtscpyxq() {
		return casebtscpyxq;
	}

	public void setCasebtscpyxq(String casebtscpyxq) {
		this.casebtscpyxq = casebtscpyxq;
	}

	@Column(name = "CASEBT", length = 1000)
	public String getCasebt() {
		return casebt;
	}

	public void setCasebt(String casebt) {
		this.casebt = casebt;
	}

	@Column(name = "CASEGJC", length = 1000)
	public String getCasegjc() {
		return casegjc;
	}

	public void setCasegjc(String casegjc) {
		this.casegjc = casegjc;
	}

	@Column(name = "CASEYWNR", length = 4000)
	public String getCaseywnr() {
		return caseywnr;
	}

	public void setCaseywnr(String caseywnr) {
		this.caseywnr = caseywnr;
	}

	@Column(name = "CASECLYJ", length = 4000)
	public String getCaseclyj() {
		return caseclyj;
	}

	public void setCaseclyj(String caseclyj) {
		this.caseclyj = caseclyj;
	}

	@Column(name = "CASEWTFLMC", length = 4000)
	public String getCasewtflmc() {
		return casewtflmc;
	}

	public void setCasewtflmc(String casewtflmc) {
		this.casewtflmc = casewtflmc;
	}

	@Column(name = "CASECPFLMC", length = 4000)
	public String getCasecpflmc() {
		return casecpflmc;
	}

	public void setCasecpflmc(String casecpflmc) {
		this.casecpflmc = casecpflmc;
	}
	
	@Column(name = "CASEWTFLCODE", length = 500)
	public String getCasewtflcode() {
		return casewtflcode;
	}

	public void setCasewtflcode(String casewtflcode) {
		this.casewtflcode = casewtflcode;
	}

	@Column(name = "CASECPFLCODE", length = 500)
	public String getCasecpflcode() {
		return casecpflcode;
	}

	public void setCasecpflcode(String casecpflcode) {
		this.casecpflcode = casecpflcode;
	}

	@Column(name = "CASEJJCD", length = 100)
	public String getCasejjcd() {
		return casejjcd;
	}

	public void setCasejjcd(String casejjcd) {
		this.casejjcd = casejjcd;
	}

	@Column(name = "CASEHFFS", length = 100)
	public String getCasehffs() {
		return casehffs;
	}

	public void setCasehffs(String casehffs) {
		this.casehffs = casehffs;
	}

	@Id
	@Column(name = "CASEID", unique = true, nullable = false, length = 22)
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@GeneratedValue(generator = "system-uuid")
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "CASEYWLY", length = 32)
	public String getCaseywly() {
		return this.caseywly;
	}

	public void setCaseywly(String caseywly) {
		this.caseywly = caseywly;
	}

	@Column(name = "CASEYWLB", length = 32)
	public String getCaseywlb() {
		return this.caseywlb;
	}

	public void setCaseywlb(String caseywlb) {
		this.caseywlb = caseywlb;
	}

	@Column(name = "CASEYWLX", length = 32)
	public String getCaseywlx() {
		return this.caseywlx;
	}

	public void setCaseywlx(String caseywlx) {
		this.caseywlx = caseywlx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 7)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "CREATER", length = 32)
	public String getCreater() {
		return this.creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	@Column(name = "CASESTATUS", length = 32)
	public String getCasestatus() {
		return this.casestatus;
	}

	public void setCasestatus(String casestatus) {
		this.casestatus = casestatus;
	}

	@Column(name = "CASEHFDZ", length = 200)
	public String getCasehfdz() {
		return casehfdz;
	}

	public void setCasehfdz(String casehfdz) {
		this.casehfdz = casehfdz;
	}

	@Column(name = "CASEBTSSFFJ", length = 1)
	public String getCasebtssffj() {
		return casebtssffj;
	}

	public void setCasebtssffj(String casebtssffj) {
		this.casebtssffj = casebtssffj;
	}

	@Column(name = "CASEDJRDW", length = 100)
	public String getCasedjrow() {
		return casedjrow;
	}

	public void setCasedjrow(String casedjrow) {
		this.casedjrow = casedjrow;
	}

	@Column(name = "JHBS", length = 2)
	public String getJhbs() {
		return jhbs;
	}

	public void setJhbs(String jhbs) {
		this.jhbs = jhbs;
	}

	@Column(name = "CYM", length = 32)
	public String getCym() {
		return cym;
	}

	public void setCym(String cym) {
		this.cym = cym;
	}

	@Column(name = "CALLID", length = 19)
	public String getCallid() {
		return callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "UPLOADFILEID", length = 32)
	public String getUploadfileid() {
		return uploadfileid;
	}

	public void setUploadfileid(String uploadfileid) {
		this.uploadfileid = uploadfileid;
	}

	@Column(name = "ORGANID", length = 32)	
	public String getOrganid() {
		return organid;
	}

	public void setOrganid(String organid) {
		this.organid = organid;
	}

	public Date getCasebjsj() {
		return casebjsj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CASEBJSJ", length = 7)
	public void setCasebjsj(Date casebjsj) {
		this.casebjsj = casebjsj;
	}

	public Date getCaseslsj() {
		return caseslsj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CASESLSJ", length = 7)
	public void setCaseslsj(Date caseslsj) {
		this.caseslsj = caseslsj;
	}

	public String getCaseqx() {
		return caseqx;
	}

	@Column(name="CASEQX", length = 10)
	public void setCaseqx(String caseqx) {
		this.caseqx = caseqx;
	}
	
	@Column(name="CREATENAME", length = 100)
	public String getCreatename() {
		return createname;
	}

	public void setCreatename(String createname) {
		this.createname = createname;
	}

}
